### PR TITLE
Code Coverage

### PR DESCRIPTION
**Pull request by craig-cogdill**

### CODE REVIEW

**Comment by john-gress** [comment]
👍

**Comment by craig-cogdill** [comment]
@KjellKod Why does this repo have Travis integration and none of the others do? It is not set up for Travis CI properly. The ```All checks have failed``` error message is misleading here, as the CI would not work even without my PR

**Comment by KjellKod** [comment]
@Craig, use git blame ;)

Hint: it wasn't me

**Comment by KjellKod** [comment]
@Craig, my suggestion is to rip out the Travis stuff. It's great to have but currently we are not using it

**Comment by craig** [comment]
Yea, let's rip out travis stuff. It's shit.

**Pull request merged**
